--------------------------------------------------------
--  파일이 생성됨 - 일요일-7월-24-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EAI_TAX_CONTRACT_TB
--------------------------------------------------------


  CREATE TABLE "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB" 
   (	"UUID" VARCHAR2(16 BYTE), 
	"CONTRACTOR_ID" VARCHAR2(8 BYTE), 
	"STATUS" CHAR(1 BYTE) DEFAULT 'N', 
	"EAI_STAT" CHAR(1 BYTE), 
	"EAI_CDATE" VARCHAR2(14 BYTE), 
	"EAI_UDATE" VARCHAR2(14 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;

   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB"."UUID" IS '문서번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB"."CONTRACTOR_ID" IS '변경 계약자';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB"."STATUS" IS '처리상태';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB"."EAI_STAT" IS 'EAI 연계상태';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB"."EAI_CDATE" IS 'EAI생성일';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB"."EAI_UDATE" IS 'EAI수정일';
   COMMENT ON TABLE "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB"  IS '세금계산서 계약자 변경정보';
--------------------------------------------------------
--  DDL for Table EAI_TAX_DETAIL_INFO_TB
--------------------------------------------------------

  CREATE TABLE "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB" 
   (	"BIZ_NO" VARCHAR2(10 BYTE), 
	"CONS_NO" VARCHAR2(12 BYTE), 
	"REQ_NO" VARCHAR2(14 BYTE), 
	"ACPTNO" VARCHAR2(18 BYTE), 
	"CONS_KND_CD" VARCHAR2(2 BYTE), 
	"ACPT_KND_NM" VARCHAR2(60 BYTE), 
	"MATRBILL_COMP_AMT" VARCHAR2(18 BYTE), 
	"COMP_AMT" VARCHAR2(18 BYTE), 
	"CUSTNM" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(60 BYTE), 
	"OPER_YMD" VARCHAR2(8 BYTE), 
	"PROF_COMP_AMT" VARCHAR2(18 BYTE), 
	"REL_SYSTEM_ID" VARCHAR2(10 BYTE) DEFAULT 'K1ETAX1022', 
	"VAT_AMT" VARCHAR2(18 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;

   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."BIZ_NO" IS '사업자번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."CONS_NO" IS '공사번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."REQ_NO" IS '발행요청일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."ACPTNO" IS '접수번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."CONS_KND_CD" IS '공사종류코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."ACPT_KND_NM" IS '접수종류명';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."MATRBILL_COMP_AMT" IS '계기공사비(내선계기), 공급가액(영업검침,조류,PPA)';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."COMP_AMT" IS '공사금액(내선계기)';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."CUSTNM" IS '고객명';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."OPER_YMD" IS '시공일자';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."PROF_COMP_AMT" IS '수익적공사금액';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."REL_SYSTEM_ID" IS '연계시스템ID K1ETAX1022=내선계기, K1NCIS1000=영업 검침원 용역 수수료, K1NDIS1000=영업 조류예방활동비';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"."VAT_AMT" IS '부가세액(PPA시스템용)';
   COMMENT ON TABLE "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB"  IS '내선계기 세금계산서 상세정보';
--------------------------------------------------------
--  DDL for Table EAI_TAX_HEADER_INFO_TB
--------------------------------------------------------

  CREATE TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" 
   (	"BIZ_NO" VARCHAR2(10 BYTE), 
	"CONS_NO" VARCHAR2(12 BYTE), 
	"REQ_NO" VARCHAR2(14 BYTE), 
	"PROF_CONS_NO" VARCHAR2(12 BYTE), 
	"CONS_NM" VARCHAR2(26 BYTE), 
	"COMP_NO" VARCHAR2(7 BYTE), 
	"PUB_YMD" VARCHAR2(8 BYTE), 
	"STATUS" VARCHAR2(3 BYTE) DEFAULT ' ', 
	"BUYER_BIZ_ID" VARCHAR2(10 BYTE), 
	"INSPECTOR_ID" VARCHAR2(8 BYTE), 
	"CONTRACTOR_ID" VARCHAR2(8 BYTE), 
	"EAI_STAT" CHAR(1 BYTE), 
	"EAI_CDATE" VARCHAR2(14 BYTE), 
	"EAI_UDATE" VARCHAR2(14 BYTE), 
	"BUYER_BIZ_CD" VARCHAR2(4 BYTE), 
	"DOC_TYPE_DETAIL" VARCHAR2(4 BYTE) DEFAULT '0101', 
	"REL_SYSTEM_ID" VARCHAR2(10 BYTE) DEFAULT 'K1ETAX1022', 
	"SMS_YN" CHAR(1 BYTE), 
	"SMS_SENDER_NAME" VARCHAR2(20 BYTE), 
	"SMS_SENDER_TEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;

   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."BIZ_NO" IS '업체 사업자번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."CONS_NO" IS '공사번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."REQ_NO" IS '발행요청일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."PROF_CONS_NO" IS '수익적공사번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."CONS_NM" IS '공사명';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."COMP_NO" IS '공사업체코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."PUB_YMD" IS '발행일';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."STATUS" IS '상태 (WRM:처음 내선계기에서 등록한상태 CFR, CFS,END등은  ETS_TAX_META_INFO_TB.STATUS_CODE와 동일함)';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."BUYER_BIZ_ID" IS '한전 사업자번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."INSPECTOR_ID" IS '검수담당자사번';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."CONTRACTOR_ID" IS '계약담당자사번';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."EAI_STAT" IS 'EAI 연계상태';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."EAI_CDATE" IS 'EAI 연계 생성일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."EAI_UDATE" IS 'EAI 연계 갱신일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."BUYER_BIZ_CD" IS '공급받는자종사업장번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."DOC_TYPE_DETAIL" IS '세금계산서종류(3.0)';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."REL_SYSTEM_ID" IS '연계시스템ID K1ETAX1022=내선계기, K1NCIS1000=영업 검침원 용역 수수료, K1NDIS1000=영업 조류예방활동비 K1PPAS1000=PPA태양광';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."SMS_YN" IS 'SMS발신여부 Y:발신, N=미발신, null=미발신';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."SMS_SENDER_NAME" IS 'SMS 발신자 이름';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"."SMS_SENDER_TEL" IS 'SMS 발신자 전화번호';
   COMMENT ON TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB"  IS '내선계기 세금계산서 헤더정보';
--------------------------------------------------------
--  DDL for Table EAI_TAX_STATUS_INFO_TB
--------------------------------------------------------

  CREATE TABLE "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB" 
   (	"BIZ_NO" VARCHAR2(10 BYTE), 
	"CONS_NO" VARCHAR2(12 BYTE), 
	"REQ_NO" VARCHAR2(14 BYTE), 
	"UUID" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(3 BYTE), 
	"STATUS_MSG" VARCHAR2(200 BYTE), 
	"SPLY_YMD" VARCHAR2(8 BYTE), 
	"EAI_STAT" CHAR(1 BYTE), 
	"EAI_CDATE" VARCHAR2(14 BYTE), 
	"EAI_UDATE" VARCHAR2(14 BYTE), 
	"NTS_ISSUE_ID" VARCHAR2(24 BYTE), 
	"REL_SYSTEM_ID" VARCHAR2(10 BYTE) DEFAULT 'K1ETAX1022', 
	"ESB_STAT" CHAR(1 BYTE), 
	"ESB_CDATE" VARCHAR2(14 BYTE), 
	"ESB_UDATE" VARCHAR2(14 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;

   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."BIZ_NO" IS '사업자번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."CONS_NO" IS '공사번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."REQ_NO" IS '발행요청일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."UUID" IS '문서번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."STATUS" IS '상태 (ETS_TAX_META_INFO_TB.DOC_STATE 값을 반영 단, 0?는 TB_TAX_BILL_INFO.STATUS_CODE 반영)';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."STATUS_MSG" IS '처리메시지 (ETS_TAX_META_INFO_TB.EXT_DOC_RESULT_MSG값 또는 국세청신고 결과 코드 반영)';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."SPLY_YMD" IS '지급일자 (STATUS값이 END인 경우 입력되면 다른 값이 후에 들어와도 null로 변경되지는 않는다 ';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."EAI_STAT" IS 'EAI상태 공백:처리전, P:처리중 C:처리완료 E:처리오류';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."EAI_CDATE" IS 'EAI생성일';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."EAI_UDATE" IS 'EAI수정일';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."NTS_ISSUE_ID" IS '국세청승인번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."REL_SYSTEM_ID" IS '연계시스템ID K1ETAX1022=내선계기, K1NCIS1000=영업 검침원 용역 수수료, K1NDIS1000=영업 조류예방활동비 K1PPAS1000=PPA태양광';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."ESB_STAT" IS 'ESB송수신상태';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."ESB_CDATE" IS 'ESB입력일자';
   COMMENT ON COLUMN "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"."ESB_UDATE" IS 'ESB변경일자';
   COMMENT ON TABLE "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB"  IS '내선계기 세금계산서 상태정보';
--------------------------------------------------------
--  DDL for Table ETAX_USER
--------------------------------------------------------

  CREATE TABLE "KEY_POWEREDI"."ETAX_USER" 
   (	"USER_ID" NUMBER(19,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"EMAIL" VARCHAR2(30 CHAR), 
	"NAME" VARCHAR2(50 CHAR), 
	"NICK_NAME" VARCHAR2(20 CHAR), 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"PROVIDER" VARCHAR2(100 CHAR), 
	"USERNAME" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Table ETAX_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "KEY_POWEREDI"."ETAX_USER_ROLES" 
   (	"ETAX_USER_USER_ID" NUMBER(19,0), 
	"ROLES" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Table IF_TAX_BILL_INFO
--------------------------------------------------------

  CREATE TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" 
   (	"REL_SYSTEM_ID" VARCHAR2(10 BYTE), 
	"JOB_GUB_CODE" VARCHAR2(6 BYTE), 
	"MANAGE_ID" VARCHAR2(24 BYTE), 
	"ADD_TAX_YN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ISSUE_ID" VARCHAR2(24 BYTE), 
	"ISSUE_DAY" VARCHAR2(8 BYTE), 
	"BILL_TYPE_CODE" VARCHAR2(4 BYTE), 
	"PURPOSE_CODE" VARCHAR2(2 BYTE), 
	"AMENDMENT_CODE" VARCHAR2(2 BYTE), 
	"UPPER_MANAGE_ID" VARCHAR2(24 BYTE), 
	"DESCRIPTION" VARCHAR2(150 BYTE), 
	"INVOICER_PARTY_ID" VARCHAR2(13 BYTE), 
	"INVOICER_TAX_REGIST_ID" VARCHAR2(4 BYTE), 
	"INVOICER_PARTY_NAME" VARCHAR2(70 BYTE), 
	"INVOICER_CEO_NAME" VARCHAR2(50 BYTE), 
	"INVOICER_ADDR" VARCHAR2(150 BYTE), 
	"INVOICER_TYPE" VARCHAR2(40 BYTE), 
	"INVOICER_CLASS" VARCHAR2(40 BYTE), 
	"INVOICER_CONTACT_DEPART" VARCHAR2(40 BYTE), 
	"INVOICER_CONTACT_NAME" VARCHAR2(30 BYTE), 
	"INVOICER_CONTACT_PHONE" VARCHAR2(20 BYTE), 
	"INVOICER_CONTACT_EMAIL" VARCHAR2(40 BYTE), 
	"INVOICEE_BUSINESS_TYPE_CODE" VARCHAR2(2 BYTE), 
	"INVOICEE_PARTY_ID" VARCHAR2(13 BYTE), 
	"INVOICEE_TAX_REGIST_ID" VARCHAR2(4 BYTE), 
	"INVOICEE_PARTY_NAME" VARCHAR2(70 BYTE), 
	"INVOICEE_CEO_NAME" VARCHAR2(30 BYTE), 
	"INVOICEE_ADDR" VARCHAR2(150 BYTE), 
	"INVOICEE_TYPE" VARCHAR2(40 BYTE), 
	"INVOICEE_CLASS" VARCHAR2(40 BYTE), 
	"INVOICEE_CONTACT_DEPART1" VARCHAR2(40 BYTE), 
	"INVOICEE_CONTACT_NAME1" VARCHAR2(30 BYTE), 
	"INVOICEE_CONTACT_PHONE1" VARCHAR2(20 BYTE), 
	"INVOICEE_CONTACT_EMAIL1" VARCHAR2(40 BYTE), 
	"INVOICEE_CONTACT_DEPART2" VARCHAR2(40 BYTE), 
	"INVOICEE_CONTACT_NAME2" VARCHAR2(30 BYTE), 
	"INVOICEE_CONTACT_PHONE2" VARCHAR2(20 BYTE), 
	"INVOICEE_CONTACT_EMAIL2" VARCHAR2(40 BYTE), 
	"PAYMENT_TYPE_CODE1" VARCHAR2(2 BYTE), 
	"PAY_AMOUNT1" NUMBER(18,0), 
	"PAYMENT_TYPE_CODE2" VARCHAR2(2 BYTE), 
	"PAY_AMOUNT2" NUMBER(18,0), 
	"PAYMENT_TYPE_CODE3" VARCHAR2(2 BYTE), 
	"PAY_AMOUNT3" NUMBER(18,0), 
	"PAYMENT_TYPE_CODE4" VARCHAR2(2 BYTE), 
	"PAY_AMOUNT4" NUMBER(18,0), 
	"CHARGE_TOTAL_AMOUNT" NUMBER(18,0), 
	"TAX_TOTAL_AMOUNT" NUMBER(18,0), 
	"GRAND_TOTAL_AMOUNT" NUMBER(18,0), 
	"CUST_NO" VARCHAR2(10 BYTE), 
	"BILL_YYYYMM" VARCHAR2(6 BYTE), 
	"BILL_ISSUE_YYYYMM" VARCHAR2(6 BYTE), 
	"PAY_DEADLINE" VARCHAR2(8 BYTE), 
	"ONLINE_GUB_CODE" VARCHAR2(1 BYTE), 
	"FLG" CHAR(1 BYTE) DEFAULT 'N', 
	"REGIST_DT" DATE DEFAULT SYSDATE, 
	"MODIFY_DT" DATE DEFAULT SYSDATE, 
	"CANCEL_DT" DATE, 
	"EAI_STAT" CHAR(1 BYTE), 
	"EAI_CDATE" VARCHAR2(14 BYTE), 
	"EAI_UDATE" VARCHAR2(14 BYTE), 
	"ERP_EVIDENCE_CODE" VARCHAR2(6 BYTE), 
	"VAT_GUB_CODE" VARCHAR2(2 BYTE), 
	"RECEIPT_GUB_CODE" VARCHAR2(1 BYTE), 
	"REGIST_ID" VARCHAR2(10 BYTE), 
	"BELNR" VARCHAR2(14 BYTE), 
	"ASP_ISSUE_ID" VARCHAR2(24 BYTE), 
	"TAX_TYPE_CODE" VARCHAR2(2 BYTE), 
	"ATTACH_FILE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;

   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."REL_SYSTEM_ID" IS '연계시스템ID';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."JOB_GUB_CODE" IS '업무구분코드(전력매출,공사매출 등)';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."MANAGE_ID" IS '사업자관리번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."ADD_TAX_YN" IS '가산세 여부';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."ISSUE_ID" IS '승인번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."ISSUE_DAY" IS '작성일자(YYYYMMDD형식): 매출기준일자';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."BILL_TYPE_CODE" IS '세금계산서종류';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."PURPOSE_CODE" IS '영수청구코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."AMENDMENT_CODE" IS '전자세금계산서 수정 사유코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."UPPER_MANAGE_ID" IS '부모관리번호 : 수정세금계산서 발행시 사용';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."DESCRIPTION" IS '비고';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_PARTY_ID" IS '공급자 사업자등록번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_TAX_REGIST_ID" IS '종사업장 식별코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_PARTY_NAME" IS '공급업체 사업체명';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_CEO_NAME" IS '공급업체 대표자명';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_ADDR" IS '공급업체의 주소';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_TYPE" IS '공급업체의 업태';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_CLASS" IS '공급업체의 업종';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_CONTACT_DEPART" IS '공급업체 담당부서';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_CONTACT_NAME" IS '공급업체 담당자명';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_CONTACT_PHONE" IS '공급업체 담당자 전화번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICER_CONTACT_EMAIL" IS '공급업체 담당자 이메일';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_BUSINESS_TYPE_CODE" IS '공급받는자 사업자등록번호 구분코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_PARTY_ID" IS '공급받는자 사업자등록번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_TAX_REGIST_ID" IS '공급받는자 종사업장 식별코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_PARTY_NAME" IS '공급받는자 사업체명';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_CEO_NAME" IS '공급받는자 대표자명';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_ADDR" IS '공급받는자 주소';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_TYPE" IS '공급받는자 업태';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_CLASS" IS '공급받는자 업종';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_CONTACT_DEPART1" IS '공급받는자 담당부서';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_CONTACT_NAME1" IS '공급받는자 담당자명';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_CONTACT_PHONE1" IS '공급받는자 담당자 전화번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_CONTACT_EMAIL1" IS '공급받는자 담당자 이메일';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_CONTACT_DEPART2" IS '공급받는자 담당부서';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_CONTACT_NAME2" IS '공급받는자 담당자명';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_CONTACT_PHONE2" IS '공급받는자 담당자 전화번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."INVOICEE_CONTACT_EMAIL2" IS '공급받는자 담당자 이메일';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."PAYMENT_TYPE_CODE1" IS '결제방법코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."PAY_AMOUNT1" IS '결제방법별금액';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."PAYMENT_TYPE_CODE2" IS '결제방법코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."PAY_AMOUNT2" IS '결제방법별금액';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."PAYMENT_TYPE_CODE3" IS '결제방법코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."PAY_AMOUNT3" IS '결제방법별금액';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."PAYMENT_TYPE_CODE4" IS '결제방법코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."PAY_AMOUNT4" IS '결제방법별금액';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."CHARGE_TOTAL_AMOUNT" IS '총 공급가액 합계';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."TAX_TOTAL_AMOUNT" IS '총 세액 합계';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."GRAND_TOTAL_AMOUNT" IS '총액(공급가액+세액)';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."CUST_NO" IS '전기고객번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."BILL_YYYYMM" IS '청구년월';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."BILL_ISSUE_YYYYMM" IS '청구서발행년월';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."PAY_DEADLINE" IS '지급만기일자';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."ONLINE_GUB_CODE" IS '온,오프라인 구분코드(1:온라인,2:오프라인, 3:요금온라인)';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."FLG" IS '처리구분(Y,N)';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."REGIST_DT" IS '등록일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."MODIFY_DT" IS '수정일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."CANCEL_DT" IS '취소일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."EAI_STAT" IS 'p:진행중 c:완료 e:에러';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."EAI_CDATE" IS 'EAI 연계 생성일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."EAI_UDATE" IS 'EAI 연계 갱신일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."ERP_EVIDENCE_CODE" IS 'ERP증빙유형코드(매입/매출공통사용)';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."VAT_GUB_CODE" IS '세금종류';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."RECEIPT_GUB_CODE" IS '접수방법 1:인편,2:우편,3이메일';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."REGIST_ID" IS '등록자 사번';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."BELNR" IS 'MM송장번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."ASP_ISSUE_ID" IS '외부발행승인번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."TAX_TYPE_CODE" IS '전자/수기구분(증빙구분) 11=ASP매입(대표메일),12=ASP매입(개별메일),13=수기입력(ASP),14=겸용서식,21=수기입력(종이)';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_INFO"."ATTACH_FILE" IS '수기분 첨부파일명';
   COMMENT ON TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO"  IS '업무시스템연계 매출세금계산서(매입증빙포함) 기본 정보';
--------------------------------------------------------
--  DDL for Table IF_TAX_BILL_ITEM_LIST
--------------------------------------------------------

  CREATE TABLE "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST" 
   (	"REL_SYSTEM_ID" VARCHAR2(10 BYTE), 
	"JOB_GUB_CODE" VARCHAR2(6 BYTE), 
	"MANAGE_ID" VARCHAR2(24 BYTE), 
	"SEQ_NO" NUMBER(2,0), 
	"PURCHASE_DAY" VARCHAR2(8 BYTE), 
	"ITEM_NAME" VARCHAR2(100 BYTE), 
	"ITEM_INFO" VARCHAR2(60 BYTE), 
	"ITEM_DESC" VARCHAR2(100 BYTE), 
	"UNIT_QUANTITY" NUMBER(12,2), 
	"UNIT_AMOUNT" NUMBER(16,2), 
	"INVOICE_AMOUNT" NUMBER(18,0), 
	"TAX_AMOUNT" NUMBER(18,0), 
	"BILL_ISSUE_YYYYMM" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;

   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."REL_SYSTEM_ID" IS '연계시스템ID';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."JOB_GUB_CODE" IS '업무구분코드(전력매출,공사매출 등)';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."MANAGE_ID" IS '사업자관리번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."SEQ_NO" IS '물품 일련번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."PURCHASE_DAY" IS '물품 공급일자';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."ITEM_NAME" IS '물품명';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."ITEM_INFO" IS '물품에 대한 규격';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."ITEM_DESC" IS '물품과 관련된 자유기술문';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."UNIT_QUANTITY" IS '수량';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."UNIT_AMOUNT" IS '물품 단가';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."INVOICE_AMOUNT" IS '물품 공급 가액';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."TAX_AMOUNT" IS '물품 세액';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"."BILL_ISSUE_YYYYMM" IS '청구발행년월';
   COMMENT ON TABLE "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST"  IS '업무시스템연계 매출세금계산서 품목 정보';
--------------------------------------------------------
--  DDL for Table IF_TAX_BILL_RESULT_INFO
--------------------------------------------------------

  CREATE TABLE "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" 
   (	"REL_SYSTEM_ID" VARCHAR2(10 BYTE), 
	"JOB_GUB_CODE" VARCHAR2(6 BYTE), 
	"MANAGE_ID" VARCHAR2(24 BYTE), 
	"STATUS_CODE" VARCHAR2(2 BYTE), 
	"STATUS_DESC" VARCHAR2(100 BYTE), 
	"REGIST_DT" DATE DEFAULT sysdate, 
	"MODIFY_DT" DATE DEFAULT sysdate, 
	"ISSUE_ID" VARCHAR2(24 BYTE), 
	"EAI_STAT" CHAR(1 BYTE), 
	"EAI_CDATE" VARCHAR2(14 BYTE), 
	"EAI_UDATE" VARCHAR2(14 BYTE), 
	"TAX_CANCEL_DATA" VARCHAR2(200 BYTE), 
	"ESERO_CREATE_TS" VARCHAR2(8 BYTE), 
	"ESERO_FINISH_TS" VARCHAR2(8 BYTE), 
	"TAX_CANCEL_DATE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;

   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."REL_SYSTEM_ID" IS '연계시스템ID';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."JOB_GUB_CODE" IS '업무구분코드(전력매출,공사매출 등)';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."MANAGE_ID" IS '사업자관리번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."STATUS_CODE" IS '처리상태코드';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."STATUS_DESC" IS '처리상태설명:오류발생시 오류내용을 기재함';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."REGIST_DT" IS '등록일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."MODIFY_DT" IS '수정일시';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."ISSUE_ID" IS '승인번호';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."EAI_STAT" IS 'EAI송수신상태  null 처리전, P 처리중  C 성공  E 실패';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."EAI_CDATE" IS 'EAI입력일자';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."EAI_UDATE" IS 'EAI변경일자';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."TAX_CANCEL_DATA" IS '업체반려사유';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."ESERO_CREATE_TS" IS '세금계산서 국세청신고등록일자(ERP 연계 안함)';
   COMMENT ON COLUMN "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"."ESERO_FINISH_TS" IS '세금계산서 국세청신고완료일자(국세청으로부터 응답문서 받은일시로 ERP에 연계하는 데이타)';
   COMMENT ON TABLE "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO"  IS '업무시스템연계 매출세금계산서(매입증빙포함) 처리결과 정보';
--------------------------------------------------------
--  DDL for Table REFRESH_TOKEN
--------------------------------------------------------

  CREATE TABLE "KEY_POWEREDI"."REFRESH_TOKEN" 
   (	"ID" NUMBER(10,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"KEY" NUMBER(19,0), 
	"TOKEN" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index EAI_TAX_CONTRACT_IDX
--------------------------------------------------------

  CREATE INDEX "KEY_POWEREDI"."EAI_TAX_CONTRACT_IDX" ON "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index EAI_TAX_DETAIL_INFO_TB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB_PK" ON "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB" ("BIZ_NO", "CONS_NO", "REQ_NO", "ACPTNO", "CONS_KND_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index EAI_TAX_HEADER_INFO_TB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB_PK" ON "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" ("BIZ_NO", "CONS_NO", "REQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index EAI_TAX_HEADER_INFO_IDX
--------------------------------------------------------

  CREATE INDEX "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_IDX" ON "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index EAI_TAX_STATUS_INFO_TB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB_PK" ON "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB" ("BIZ_NO", "CONS_NO", "REQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index EAI_TAX_STATUS_INFO_IDX
--------------------------------------------------------

  CREATE INDEX "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_IDX" ON "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index EAI_TAX_STATUS_INFO_TB_IX01
--------------------------------------------------------

  CREATE INDEX "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB_IX01" ON "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB" ("REL_SYSTEM_ID", "CONS_NO", "REQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index SYS_C008651
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEY_POWEREDI"."SYS_C008651" ON "KEY_POWEREDI"."ETAX_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index UK_EL4J3UCEOC8TOLGIMT43L5YP9
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEY_POWEREDI"."UK_EL4J3UCEOC8TOLGIMT43L5YP9" ON "KEY_POWEREDI"."ETAX_USER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index IF_TAX_BILL_INFO_IX1
--------------------------------------------------------

  CREATE INDEX "KEY_POWEREDI"."IF_TAX_BILL_INFO_IX1" ON "KEY_POWEREDI"."IF_TAX_BILL_INFO" ("ONLINE_GUB_CODE", "FLG", "ISSUE_DAY", "MODIFY_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index IF_TAX_BILL_INFO_IX2
--------------------------------------------------------

  CREATE INDEX "KEY_POWEREDI"."IF_TAX_BILL_INFO_IX2" ON "KEY_POWEREDI"."IF_TAX_BILL_INFO" ("REL_SYSTEM_ID", "BILL_ISSUE_YYYYMM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index IF_TAX_BILL_INFO_IX3
--------------------------------------------------------

  CREATE INDEX "KEY_POWEREDI"."IF_TAX_BILL_INFO_IX3" ON "KEY_POWEREDI"."IF_TAX_BILL_INFO" ("REL_SYSTEM_ID", "EAI_STAT", "REGIST_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index IF_TAX_BILL_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEY_POWEREDI"."IF_TAX_BILL_INFO_PK" ON "KEY_POWEREDI"."IF_TAX_BILL_INFO" ("REL_SYSTEM_ID", "JOB_GUB_CODE", "MANAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index IF_TAX_BILL_INFO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEY_POWEREDI"."IF_TAX_BILL_INFO_UK" ON "KEY_POWEREDI"."IF_TAX_BILL_INFO" ("ISSUE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index IF_TAX_BILL_ITEM_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST_PK" ON "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST" ("REL_SYSTEM_ID", "JOB_GUB_CODE", "MANAGE_ID", "SEQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index IF_TAX_BILL_RESULT_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO_PK" ON "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" ("REL_SYSTEM_ID", "JOB_GUB_CODE", "MANAGE_ID", "STATUS_CODE", "REGIST_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index IF_TAX_BILL_RESULT_INFO_IX01
--------------------------------------------------------

  CREATE INDEX "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO_IX01" ON "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" ("REL_SYSTEM_ID", "EAI_STAT", "MODIFY_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  DDL for Index SYS_C008658
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEY_POWEREDI"."SYS_C008658" ON "KEY_POWEREDI"."REFRESH_TOKEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI" ;
--------------------------------------------------------
--  Constraints for Table EAI_TAX_CONTRACT_TB
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB" MODIFY ("CONTRACTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_CONTRACT_TB" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAI_TAX_DETAIL_INFO_TB
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB" MODIFY ("BIZ_NO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB" MODIFY ("CONS_NO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB" MODIFY ("REQ_NO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB" MODIFY ("ACPTNO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_DETAIL_INFO_TB" MODIFY ("CONS_KND_CD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAI_TAX_HEADER_INFO_TB
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" MODIFY ("BIZ_NO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" MODIFY ("CONS_NO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" MODIFY ("REQ_NO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" MODIFY ("PUB_YMD" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" MODIFY ("BUYER_BIZ_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" MODIFY ("INSPECTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" MODIFY ("CONTRACTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_HEADER_INFO_TB" MODIFY ("REL_SYSTEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAI_TAX_STATUS_INFO_TB
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB" MODIFY ("BIZ_NO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB" MODIFY ("CONS_NO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB" MODIFY ("REQ_NO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."EAI_TAX_STATUS_INFO_TB" MODIFY ("REL_SYSTEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ETAX_USER
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."ETAX_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."ETAX_USER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."ETAX_USER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."ETAX_USER" MODIFY ("NICK_NAME" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."ETAX_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."ETAX_USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI"  ENABLE;
  ALTER TABLE "KEY_POWEREDI"."ETAX_USER" ADD CONSTRAINT "UK_EL4J3UCEOC8TOLGIMT43L5YP9" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ETAX_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."ETAX_USER_ROLES" MODIFY ("ETAX_USER_USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IF_TAX_BILL_INFO
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("REL_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("JOB_GUB_CODE" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("MANAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("ISSUE_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("ISSUE_DAY" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("BILL_TYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("INVOICER_PARTY_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("INVOICER_PARTY_NAME" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("INVOICER_CEO_NAME" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("INVOICEE_BUSINESS_TYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("INVOICEE_PARTY_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("INVOICEE_PARTY_NAME" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("INVOICEE_CEO_NAME" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("INVOICEE_ADDR" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("PAYMENT_TYPE_CODE1" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("PAY_AMOUNT1" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("CHARGE_TOTAL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("TAX_TOTAL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("GRAND_TOTAL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("ONLINE_GUB_CODE" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("FLG" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("REGIST_DT" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" MODIFY ("MODIFY_DT" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_INFO" ADD PRIMARY KEY ("REL_SYSTEM_ID", "JOB_GUB_CODE", "MANAGE_ID")
  USING INDEX "KEY_POWEREDI"."IF_TAX_BILL_INFO_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IF_TAX_BILL_ITEM_LIST
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST" MODIFY ("REL_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST" MODIFY ("JOB_GUB_CODE" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST" MODIFY ("MANAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST" MODIFY ("SEQ_NO" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST" ADD PRIMARY KEY ("REL_SYSTEM_ID", "JOB_GUB_CODE", "MANAGE_ID", "SEQ_NO")
  USING INDEX "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IF_TAX_BILL_RESULT_INFO
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" MODIFY ("REL_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" MODIFY ("JOB_GUB_CODE" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" MODIFY ("MANAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" MODIFY ("STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" MODIFY ("REGIST_DT" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" MODIFY ("MODIFY_DT" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" MODIFY ("ISSUE_ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO" ADD PRIMARY KEY ("REL_SYSTEM_ID", "JOB_GUB_CODE", "MANAGE_ID", "STATUS_CODE", "REGIST_DT")
  USING INDEX "KEY_POWEREDI"."IF_TAX_BILL_RESULT_INFO_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REFRESH_TOKEN
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."REFRESH_TOKEN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."REFRESH_TOKEN" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."REFRESH_TOKEN" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "KEY_POWEREDI"."REFRESH_TOKEN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEY_POWEREDI"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ETAX_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."ETAX_USER_ROLES" ADD CONSTRAINT "FKCU4XR4PTIWW6EOWRJU6CRN9IR" FOREIGN KEY ("ETAX_USER_USER_ID")
	  REFERENCES "KEY_POWEREDI"."ETAX_USER" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IF_TAX_BILL_ITEM_LIST
--------------------------------------------------------

  ALTER TABLE "KEY_POWEREDI"."IF_TAX_BILL_ITEM_LIST" ADD FOREIGN KEY ("REL_SYSTEM_ID", "JOB_GUB_CODE", "MANAGE_ID")
	  REFERENCES "KEY_POWEREDI"."IF_TAX_BILL_INFO" ("REL_SYSTEM_ID", "JOB_GUB_CODE", "MANAGE_ID") ENABLE;
