spring:
    profiles:
        active: dev

    freemarker:
        template-loader-path: classpath:/templates
        suffix: .ftl

    messages:
        basename: i18n/exception
        encoding: UTF-8

logging:
    config: classpath:logback/logback-spring.xml

jwt:
    access:
        expiration: 180 # 3시간 600 * 3
    refresh:
        expiration: 365 # 1년

