server:
  port: 9080
spring:
  datasource:
    password:
    url: jdbc:log4jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=ON)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=168.78.211.152)(PORT=21152))(ADDRESS=(PROTOCOL=TCP)(HOST=168.78.211.156)(PORT=21152)))(CONNECT_DATA=(SERVICE_NAME=CATG)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))
    username: KEY_POWEREDI
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  charset:
    console: UTF-8
  level:
    root: warn
    com.kepco.etax.api.EtaxRestApiApplication: info
  file:
    path: ./api/log

  logback:
    rollingpolicy:
      max-history: 7
