server:
  port: 9080
spring:
  datasource:
    password:
    url: jdbc:oracle:thin:@janakena111.iptime.org:1521:ORCLDB
    username: KEY_POWEREDI
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  charset:
    console: UTF-8
  level:
    root: warn
    com.kepco.etax.api.EtaxRestApiApplication: info
  file:
    path: ./api/log

  logback:
    rollingpolicy:
      max-history: 7
