server:
  port: 9080
spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  charset:
    console: UTF-8
  level:
    root: warn
    com.kepco.etax.api.EtaxRestApiApplication: info
  file:
    path: ./api/log

  logback:
    rollingpolicy:
      max-history: 15
