package com.kepco.etax.api.domain.response;

import com.kepco.etax.api.domain.entity.IfTaxBillInfoEntity;
import lombok.Getter;
import org.springframework.beans.BeanUtils;

import java.time.LocalDateTime;

@Getter
public class IfTaxBillInfoResponse {

    private String relSystemId;
    private String jobGubCode;
    private String manageId;
    private String addTaxYn;
    private String issueId;
    private String issueDay;
    private String billTypeCode;
    private String purposeCode;
    private String amendmentCode;
    private String upperManageId;
    private String description;
    private String invoicerPartyId;
    private String invoicerTaxRegistId;
    private String invoicerPartyName;
    private String invoicerCeoName;
    private String invoicerAddr;
    private String invoicerType;
    private String invoicerClass;
    private String invoicerContactDepart;
    private String invoicerContactName;
    private String invoicerContactPhone;
    private String invoicerContactEmail;
    private String invoiceeBusinessTypeCode;
    private String invoiceePartyId;
    private String invoiceeTaxRegistId;
    private String invoiceePartyName;
    private String invoiceeCeoName;
    private String invoiceeAddr;
    private String invoiceeType;
    private String invoiceeClass;
    private String invoiceeContactDepart1;
    private String invoiceeContactName1;
    private String invoiceeContactPhone1;
    private String invoiceeContactEmail1;
    private String invoiceeContactDepart2;
    private String invoiceeContactName2;
    private String invoiceeContactPhone2;
    private String invoiceeContactEmail2;
    private String paymentTypeCode1;
    private long payAmount1;
    private String paymentTypeCode2;
    private long payAmount2;
    private String paymentTypeCode3;
    private long payAmount3;
    private String paymentTypeCode4;
    private long payAmount4;
    private long chargeTotalAmount;
    private long taxTotalAmount;
    private long grandTotalAmount;
    private String custNo;
    private String billYyyymm;
    private String billIssueYyyymm;
    private String payDeadline;
    private String onlineGubCode;
    private String flg;
    private LocalDateTime registDt;
    private LocalDateTime modifyDt;
    private LocalDateTime cancelDt;
    private String eaiStat;
    private String eaiCdate;
    private String eaiUdate;
    private String erpEvidenceCode;
    private String vatGubCode;
    private String receiptGubCode;
    private String registId;
    private String belnr;
    private String aspIssueId;
    private String taxTypeCode;
    private String attachFile;

    public IfTaxBillInfoResponse(IfTaxBillInfoEntity data) {
        this.jobGubCode = data.getIfTaxBillInfoKey().getJobGubCode();
        this.manageId = data.getIfTaxBillInfoKey().getManageId();
        this.relSystemId = data.getIfTaxBillInfoKey().getRelSystemId();
        this.addTaxYn  = data.getAddTaxYn();
        this.issueId  = data.getIssueId();
        this.issueDay  = data.getIssueDay();
        this.billTypeCode  = data.getBillTypeCode();
        this.purposeCode  = data.getPurposeCode();
        this.amendmentCode  = data.getAmendmentCode();
        this.upperManageId  = data.getUpperManageId();
        this.description  = data.getDescription();
        this.invoicerPartyId  = data.getInvoicerPartyId();
        this.invoicerTaxRegistId  = data.getInvoicerTaxRegistId();
        this.invoicerPartyName  = data.getInvoicerPartyName();
        this.invoicerCeoName  = data.getInvoicerCeoName();
        this.invoicerAddr  = data.getInvoicerAddr();
        this.invoicerType  = data.getInvoicerType();
        this.invoicerClass  = data.getInvoicerClass();
        this.invoicerContactDepart  = data.getInvoicerContactDepart();
        this.invoicerContactName  = data.getInvoicerContactName();
        this.invoicerContactPhone  = data.getInvoicerContactPhone();
        this.invoicerContactEmail  = data.getInvoicerContactEmail();
        this.invoiceeBusinessTypeCode  = data.getInvoiceeBusinessTypeCode();
        this.invoiceePartyId  = data.getInvoiceePartyId();
        this.invoiceeTaxRegistId  = data.getInvoiceeTaxRegistId();
        this.invoiceePartyName  = data.getInvoiceePartyName();
        this.invoiceeCeoName  = data.getInvoiceeCeoName();
        this.invoiceeAddr  = data.getInvoiceeAddr();
        this.invoiceeType  = data.getInvoiceeType();
        this.invoiceeClass  = data.getInvoiceeClass();
        this.invoiceeContactDepart1  = data.getInvoiceeContactDepart1();
        this.invoiceeContactName1  = data.getInvoiceeContactName1();
        this.invoiceeContactPhone1  = data.getInvoiceeContactPhone1();
        this.invoiceeContactEmail1  = data.getInvoiceeContactEmail1();
        this.invoiceeContactDepart2  = data.getInvoiceeContactDepart2();
        this.invoiceeContactName2  = data.getInvoiceeContactName2();
        this.invoiceeContactPhone2  = data.getInvoiceeContactPhone2();
        this.invoiceeContactEmail2  = data.getInvoiceeContactEmail2();
        this.paymentTypeCode1  = data.getPaymentTypeCode1();
        this.payAmount1  = data.getPayAmount1();
        this.paymentTypeCode2  = data.getPaymentTypeCode2();
        this.payAmount2  = data.getPayAmount2();
        this.paymentTypeCode3  = data.getPaymentTypeCode3();
        this.payAmount3  = data.getPayAmount3();
        this.paymentTypeCode4  = data.getPaymentTypeCode4();
        this.payAmount4  = data.getPayAmount4();
        this.chargeTotalAmount  = data.getChargeTotalAmount();
        this.taxTotalAmount  = data.getTaxTotalAmount();
        this.grandTotalAmount  = data.getGrandTotalAmount();
        this.custNo  = data.getCustNo();
        this.billYyyymm  = data.getBillYyyymm();
        this.billIssueYyyymm  = data.getBillIssueYyyymm();
        this.payDeadline  = data.getPayDeadline();
        this.onlineGubCode  = data.getOnlineGubCode();
        this.flg  = data.getFlg();
        this.registDt  = data.getRegistDt();
        this.modifyDt  = data.getModifyDt();
        this.cancelDt  = data.getCancelDt();
        this.eaiStat  = data.getEaiStat();
        this.eaiCdate  = data.getEaiCdate();
        this.eaiUdate  = data.getEaiUdate();
        this.erpEvidenceCode  = data.getErpEvidenceCode();
        this.vatGubCode  = data.getVatGubCode();
        this.receiptGubCode  = data.getReceiptGubCode();
        this.registId  = data.getRegistId();
        this.belnr  = data.getBelnr();
        this.aspIssueId  = data.getAspIssueId();
        this.taxTypeCode  = data.getTaxTypeCode();
        this.attachFile  = data.getAttachFile();
    }

}
